// Your universal tip address on all chains
// One address on every chain
export const TIP_UNIVERSAL_ADDRESS =
  '0x25b3Ea33069428dCD1f268F1c6139701F1dC0137'

// For future flexibility if you ever change a specific chain
export const TIP_ADDRESS_BY_CHAIN = {
  1: TIP_UNIVERSAL_ADDRESS, // Ethereum
  10: TIP_UNIVERSAL_ADDRESS, // Optimism
  56: TIP_UNIVERSAL_ADDRESS, // BNB
  100: TIP_UNIVERSAL_ADDRESS, // Gnosis
  137: TIP_UNIVERSAL_ADDRESS, // Polygon
  195: TIP_UNIVERSAL_ADDRESS, // X1
  250: TIP_UNIVERSAL_ADDRESS, // Fantom
  1329: TIP_UNIVERSAL_ADDRESS, // Sei
  8453: TIP_UNIVERSAL_ADDRESS, // Base
  34443: TIP_UNIVERSAL_ADDRESS, // Mode
  42161: TIP_UNIVERSAL_ADDRESS, // Arbitrum
  43114: TIP_UNIVERSAL_ADDRESS, // Avalanche
  59144: TIP_UNIVERSAL_ADDRESS, // Linea
  80094: TIP_UNIVERSAL_ADDRESS, // Berachain
  7777777: TIP_UNIVERSAL_ADDRESS, // Zora
  130: TIP_UNIVERSAL_ADDRESS, // Unichain
  42220: TIP_UNIVERSAL_ADDRESS, // Celo
  1313161554: TIP_UNIVERSAL_ADDRESS, // Aurora
  1284: TIP_UNIVERSAL_ADDRESS, // Moonbeam
  1285: TIP_UNIVERSAL_ADDRESS, // Moonriver
  5000: TIP_UNIVERSAL_ADDRESS, // Mantle
  9745: TIP_UNIVERSAL_ADDRESS, // Plasma
  14: TIP_UNIVERSAL_ADDRESS, // Flare
  40: TIP_UNIVERSAL_ADDRESS, // Telos
  50: TIP_UNIVERSAL_ADDRESS, // XDC
  57: TIP_UNIVERSAL_ADDRESS, // Syscoin
  61: TIP_UNIVERSAL_ADDRESS, // ETC
  57073: TIP_UNIVERSAL_ADDRESS, // Inkonchain
  60808: TIP_UNIVERSAL_ADDRESS, // BOB
  81457: TIP_UNIVERSAL_ADDRESS, // Blast
  1868: TIP_UNIVERSAL_ADDRESS, // Soneium
  480: TIP_UNIVERSAL_ADDRESS, // World Chain
  1135: TIP_UNIVERSAL_ADDRESS, // Lisk
  1923: TIP_UNIVERSAL_ADDRESS, // Swellchain
  2741: TIP_UNIVERSAL_ADDRESS, // Abstract
  747474: TIP_UNIVERSAL_ADDRESS, // Katana
  146: TIP_UNIVERSAL_ADDRESS // Sonic
}
export const TIP_DEFAULT_CHAIN_ID = 1;

// suggested native-amount presets
export const TIP_SUGGESTED_AMOUNTS = ['0.0005', '0.0015', '0.005'];